/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_12;

import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class Principal extends javax.swing.JFrame {

        float num1 = 999999;
        float num2 = 999999;
        float resultado;
        
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSumar = new javax.swing.JLabel();
        btnResta = new javax.swing.JLabel();
        btnDividir = new javax.swing.JLabel();
        btnMultiplicar = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número 1:");

        jLabel2.setText("Número 2:");

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel3.setText("Calculadora");

        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSumar.png"))); // NOI18N
        btnSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSumarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSumarMouseExited(evt);
            }
        });

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnResta.png"))); // NOI18N
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestaMouseExited(evt);
            }
        });

        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDividir.png"))); // NOI18N
        btnDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDividirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDividirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDividirMouseExited(evt);
            }
        });

        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnMultiplicar.png"))); // NOI18N
        btnMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultiplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultiplicarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnDividir)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnMultiplicar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSumar)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnResta)))
                                .addGap(18, 18, 18)
                                .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(txtNum1))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSumar)
                            .addComponent(btnResta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDividir)
                            .addComponent(btnMultiplicar))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumarMouseClicked
        getNumeros();
        resultado = num1 + num2;
        setResultado();
    }//GEN-LAST:event_btnSumarMouseClicked

    private void btnSumarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumarMouseEntered
        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSumarActive.png")));
    }//GEN-LAST:event_btnSumarMouseEntered

    private void btnSumarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumarMouseExited
        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSumar.png")));
    }//GEN-LAST:event_btnSumarMouseExited

    private void btnRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseClicked
        getNumeros();
        resultado = num1 - num2;
        setResultado();
    }//GEN-LAST:event_btnRestaMouseClicked

    private void btnRestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseEntered
        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRestaActive.png")));
    }//GEN-LAST:event_btnRestaMouseEntered

    private void btnRestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseExited
        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnResta.png")));
    }//GEN-LAST:event_btnRestaMouseExited

    private void btnDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDividirMouseClicked
        getNumeros();
       
        if (num1 == 0 && num2 == 0){
            JOptionPane.showInternalMessageDialog(
                null, 
                "No se puede dividir 0 entre 0.", 
                "ERROR", 
                JOptionPane.ERROR_MESSAGE
            );               
                            
            txtNum1.setText("");
            txtNum2.setText("");
            txtResultado.setText("");
            return;
        }
        else if (num1 == 0 || num2 == 0){
            JOptionPane.showInternalMessageDialog(
                null, 
                "No se puede dividir entre 0.", 
                "ERROR", 
                JOptionPane.ERROR_MESSAGE
            );
          
            txtNum1.setText("");
            txtNum2.setText("");
            txtResultado.setText("");
            return;
        }
            
        resultado = num1 / num2;

        setResultado();
    }//GEN-LAST:event_btnDividirMouseClicked

    private void btnDividirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDividirMouseEntered
        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDividirActive.png")));
    }//GEN-LAST:event_btnDividirMouseEntered

    private void btnDividirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDividirMouseExited
        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDividir.png")));
    }//GEN-LAST:event_btnDividirMouseExited

    private void btnMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicarMouseClicked
        getNumeros();
        resultado = num1 * num2;
        setResultado();
    }//GEN-LAST:event_btnMultiplicarMouseClicked

    private void btnMultiplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicarMouseEntered
        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnMultiplicarActive.png")));
    }//GEN-LAST:event_btnMultiplicarMouseEntered

    private void btnMultiplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicarMouseExited
        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnMultiplicar.png")));
    }//GEN-LAST:event_btnMultiplicarMouseExited

    public void getNumeros(){
        num1 = 999999;
        num2 = 999999;
        try{
            num1 = Integer.parseInt(txtNum1.getText());
            num2 = Integer.parseInt(txtNum2.getText());
        } catch (NumberFormatException ex){

            if (num1 == 999999){
                JOptionPane.showInternalMessageDialog(
                null, 
                "Se deben ingresar valores númericos.", 
                "ERROR", 
                JOptionPane.ERROR_MESSAGE);
            
                txtNum1.setText("");
                txtNum2.setText("");
                txtResultado.setText("");
            } else if (num2 == 999999){
                JOptionPane.showInternalMessageDialog(
                null, 
                "Se deben ingresar valores númericos.", 
                "ERROR", 
                JOptionPane.ERROR_MESSAGE);
                
                num1 = 999999;
                num2 = 999999;
                txtNum1.setText("");
                txtNum2.setText("");
                txtResultado.setText("");
            }   
        } finally {
            
        }  
    }
    
    public void setResultado(){
        if(num1 != 999999 && num2 != 999999){
            txtResultado.setText(String.valueOf(resultado));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDividir;
    private javax.swing.JLabel btnMultiplicar;
    private javax.swing.JLabel btnResta;
    private javax.swing.JLabel btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
